/* QRKit Signal Paper: guides are practical editorial content, each with one clear takeaway and a route back to the right tool. */
export type BlogArticle = {slug:string;title:string;excerpt:string;readTime:string;toolPath:string;sections:{heading:string;body:string}[]};
export const articles:BlogArticle[]=[
 {slug:'how-to-create-a-qr-code',title:'How to Create a QR Code',excerpt:'A practical three-step guide to turning a link, note, or contact detail into a code people can actually scan.',readTime:'4 min read',toolPath:'/qr-code-generator',sections:[{heading:'Start with the destination',body:'Choose the content that should open after the scan. A short, stable URL is usually the clearest starting point; for plain text, keep the message concise enough for the scanning app to display comfortably.'},{heading:'Check before you publish',body:'A QR code is only useful when the final artwork preserves quiet space around the modules. Generate the code, scan it from the distance your audience will use, then export SVG for print or PNG for quick digital sharing.'},{heading:'Static or dynamic?',body:'A static code stores its destination directly in the pattern. That keeps it private and dependable. A dynamic code can point through a redirect you control, which is useful when the destination or analytics requirements may change later.'}]},
 {slug:'how-to-create-a-wifi-qr-code',title:'How to Create a WiFi QR Code',excerpt:'Make guest access simpler without putting a network password on a paper sign in plain text.',readTime:'3 min read',toolPath:'/wifi-qr-code',sections:[{heading:'Use the network’s exact name',body:'The SSID is case-sensitive. Copy it carefully, choose WPA, WEP, or no password, and mark hidden networks only when the network is actually hidden.'},{heading:'Protect the printout',body:'A WiFi code is convenient, but anyone who can scan it may receive the network credentials. Place it where guests can use it without exposing your private network.'}]},
 {slug:'qr-code-for-a-business-card',title:'QR Code for a Business Card',excerpt:'Pair a compact printed card with a vCard so people can save your details without typing them.',readTime:'4 min read',toolPath:'/vcard-qr-code',sections:[{heading:'Keep the vCard complete',body:'Include the person’s name, organization, role, phone, email, and website. The QR pattern should support the amount of information without becoming too dense for the intended print size.'},{heading:'Design around the scan',body:'Leave quiet space around the code and test on both iOS and Android. A simple black-on-light treatment remains the safest default for small business cards.'}]},
 {slug:'static-qr-vs-dynamic-qr',title:'Static QR vs Dynamic QR',excerpt:'Understand the trade-off between a private, self-contained code and a redirect you can update later.',readTime:'5 min read',toolPath:'/qr-code-generator',sections:[{heading:'Static QR codes',body:'The destination is encoded directly in the pattern. They can be generated entirely in the browser, do not require a redirect service, and are a strong fit for permanent links, WiFi access, and contact cards.'},{heading:'Dynamic QR codes',body:'A dynamic code points to a redirect such as `/r/abc123`. The redirect service can change the destination and record scans, but it introduces an operational dependency and a need for careful privacy design.'}]},
 {slug:'what-is-a-code-128-barcode',title:'What Is a Code 128 Barcode?',excerpt:'A concise introduction to the high-density barcode standard used across labels, logistics, and internal inventory.',readTime:'4 min read',toolPath:'/code-128-generator',sections:[{heading:'Why teams use it',body:'Code 128 packs a broad character set into a compact linear symbol, which makes it useful when labels have limited width but still need letters and numbers.'},{heading:'Validate the real label',body:'Generate the barcode, keep the human-readable value visible when appropriate, and scan the final printed label at the distance and contrast your workflow requires.'}]},
 {slug:'ean-13-vs-upc-a',title:'EAN-13 vs UPC-A',excerpt:'Know which retail barcode family fits your product number before you export artwork.',readTime:'4 min read',toolPath:'/ean-13-barcode-generator',sections:[{heading:'The practical difference',body:'UPC-A is the familiar 12-digit retail format used widely in North America. EAN-13 adds one leading digit and is common across international retail systems.'},{heading:'Checksum matters',body:'Both formats include a check digit. QRKit calculates it for shorter inputs and rejects a complete value when the supplied checksum does not match.'}]},
];
articles.push(
 {slug:'qr-code-for-a-restaurant-menu',title:'How to Create a QR Code for a Restaurant Menu',excerpt:'A practical checklist for menu QR codes that remain legible on tables, windows, and takeaway packaging.',readTime:'4 min read',toolPath:'/url-to-qr-code',sections:[{heading:'Choose a stable menu URL',body:'Use a short, mobile-friendly URL that opens directly to the current menu. Avoid putting a long tracking string into the pattern when a clean destination will do.'},{heading:'Design for table distance',body:'Tabletop codes are often scanned from an awkward angle. Keep strong contrast, enough quiet space, and a size that gives the camera room to focus.'}]},
 {slug:'qr-code-for-google-maps',title:'How to Create a QR Code for Google Maps',excerpt:'Share a map destination for a shop, venue, or meeting point without asking visitors to type an address.',readTime:'3 min read',toolPath:'/location-qr-code',sections:[{heading:'Use the exact pin',body:'Copy the share link or use coordinates for the location you want visitors to reach. A precise pin is more useful than a broad street address for entrances and temporary venues.'},{heading:'Test the handoff',body:'Scan from the printed size and confirm the map app opens the right place. Check both a phone on WiFi and a phone using mobile data.'}]},
 {slug:'what-is-a-dynamic-qr-code',title:'What Is a Dynamic QR Code?',excerpt:'Learn how redirect-based QR codes can change destinations and report scans, and where the extra operational complexity comes from.',readTime:'5 min read',toolPath:'/pricing',sections:[{heading:'The redirect model',body:'A dynamic code stores a redirect URL such as `/r/abc123` instead of the final destination. A Worker can look up the active destination, record a scan event, and return a 302 redirect.'},{heading:'Plan privacy before analytics',body:'Scan counts can be useful for campaigns, but country, device, browser, referrer, and timestamps should be collected intentionally and documented clearly.'}]},
);
export function articleBySlug(slug:string){return articles.find(article=>article.slug===slug)}
