/* QRKit Signal Paper: content architecture stays editorial and structured; this module keeps generator engines separate from UI. */
export type ToolKind = 'qr' | 'barcode';
export type ToolConfig = { slug:string; name:string; kind:ToolKind; description:string; category:string; seoTitle:string; seoDescription:string; defaultValue:string; format?:string; };
export const qrTools:ToolConfig[] = [
 {slug:'qr-code-generator',name:'QR Code Generator',kind:'qr',description:'Create a custom QR code for any URL or text.',category:'QR Code',seoTitle:'QR Code Generator – Create Free QR Codes',seoDescription:'Create a free QR code online with instant browser-based generation and PNG or SVG export.',defaultValue:'https://qrkit.example'},
 {slug:'url-to-qr-code',name:'URL QR Code',kind:'qr',description:'Turn a website link into a scannable QR code.',category:'QR Code',seoTitle:'URL to QR Code Generator – Free Online Tool',seoDescription:'Convert any URL into a free QR code and download it instantly.',defaultValue:'https://qrkit.example'},
 {slug:'text-to-qr-code',name:'Text QR Code',kind:'qr',description:'Encode notes, instructions, or any text locally.',category:'QR Code',seoTitle:'Text to QR Code Generator – Free Tool',seoDescription:'Create a QR code from plain text with private, local browser processing.',defaultValue:'Scan this with QRKit.'},
 {slug:'wifi-qr-code',name:'WiFi QR Code',kind:'qr',description:'Let guests join a WiFi network without typing a password.',category:'QR Code',seoTitle:'WiFi QR Code Generator – Create Free WiFi QR Codes',seoDescription:'Create a free WiFi QR code to let people connect to your wireless network instantly.',defaultValue:'QRKit Guest'},
 {slug:'email-qr-code',name:'Email QR Code',kind:'qr',description:'Open a pre-filled email with one quick scan.',category:'QR Code',seoTitle:'Email QR Code Generator – Free Online Tool',seoDescription:'Create an email QR code with recipient, subject, and message fields.',defaultValue:'hello@example.com'},
 {slug:'phone-qr-code',name:'Phone QR Code',kind:'qr',description:'Make a QR code that starts a phone call.',category:'QR Code',seoTitle:'Phone QR Code Generator – Free Tool',seoDescription:'Create a QR code for a phone number and let people call instantly.',defaultValue:'+1 555 010 2048'},
 {slug:'sms-qr-code',name:'SMS QR Code',kind:'qr',description:'Create a scan-to-text message for events and campaigns.',category:'QR Code',seoTitle:'SMS QR Code Generator – Free Online Tool',seoDescription:'Generate an SMS QR code with a recipient and optional message.',defaultValue:'+1 555 010 2048'},
 {slug:'vcard-qr-code',name:'vCard QR Code',kind:'qr',description:'Share a digital business card from a single scan.',category:'QR Code',seoTitle:'vCard QR Code Generator – Free Business Card Tool',seoDescription:'Create a vCard QR code with contact details, website, and organization.',defaultValue:'Alex Morgan'},
 {slug:'location-qr-code',name:'Location QR Code',kind:'qr',description:'Share a precise map location or address.',category:'QR Code',seoTitle:'Location QR Code Generator – Free Map QR Code',seoDescription:'Create a location QR code from coordinates or an address.',defaultValue:'40.7128,-74.0060'},
 {slug:'whatsapp-qr-code',name:'WhatsApp QR Code',kind:'qr',description:'Start a WhatsApp chat from a scan.',category:'QR Code',seoTitle:'WhatsApp QR Code Generator – Free Tool',seoDescription:'Create a WhatsApp QR code for a phone number and optional message.',defaultValue:'15550102048'},
 {slug:'event-qr-code',name:'Event QR Code',kind:'qr',description:'Put event details into a shareable calendar QR code.',category:'QR Code',seoTitle:'Event QR Code Generator – Free Calendar QR Code',seoDescription:'Create an event QR code with date, time, location, and description.',defaultValue:'QRKit Workshop'},
];
export const barcodeTools:ToolConfig[] = [
 {slug:'barcode-generator',name:'Barcode Generator',kind:'barcode',description:'Create and download a barcode in seconds.',category:'Barcode',seoTitle:'Barcode Generator – Create Free Barcodes Online',seoDescription:'Generate Code 128, EAN-13, UPC-A, Code 39, ITF-14, and ISBN barcodes.',defaultValue:'QRKIT2026',format:'CODE128'},
 {slug:'code-128-generator',name:'Code 128',kind:'barcode',description:'A compact, high-density barcode for logistics and labels.',category:'Barcode',seoTitle:'Code 128 Barcode Generator – Free Online Tool',seoDescription:'Generate a valid Code 128 barcode with instant PNG and SVG downloads.',defaultValue:'QRKIT2026',format:'CODE128'},
 {slug:'ean-13-barcode-generator',name:'EAN-13',kind:'barcode',description:'Generate retail-ready EAN-13 barcodes with checksum validation.',category:'Barcode',seoTitle:'EAN-13 Barcode Generator – Free Tool',seoDescription:'Create a valid EAN-13 barcode and automatically calculate or validate its checksum.',defaultValue:'590123412345',format:'EAN13'},
 {slug:'upc-a-barcode-generator',name:'UPC-A',kind:'barcode',description:'Create a standard 12-digit UPC-A retail barcode.',category:'Barcode',seoTitle:'UPC-A Barcode Generator – Free Tool',seoDescription:'Generate a valid UPC-A barcode with automatic checksum handling.',defaultValue:'03600029145',format:'UPC'},
 {slug:'code-39-barcode-generator',name:'Code 39',kind:'barcode',description:'A durable alphanumeric barcode for industrial use.',category:'Barcode',seoTitle:'Code 39 Barcode Generator – Free Online Tool',seoDescription:'Generate a Code 39 barcode from supported letters, numbers, and symbols.',defaultValue:'QRKIT-39',format:'CODE39'},
 {slug:'itf-14-barcode-generator',name:'ITF-14',kind:'barcode',description:'Create shipping and carton barcodes with a calculated check digit.',category:'Barcode',seoTitle:'ITF-14 Barcode Generator – Free Tool',seoDescription:'Generate a valid ITF-14 shipping barcode from 13 digits.',defaultValue:'100123456789',format:'ITF14'},
 {slug:'isbn-barcode-generator',name:'ISBN Barcode',kind:'barcode',description:'Validate ISBN-10 or ISBN-13 before generating a barcode.',category:'Barcode',seoTitle:'ISBN Barcode Generator – Free Tool',seoDescription:'Create an ISBN barcode with checksum validation for ISBN-10 and ISBN-13.',defaultValue:'9780306406157',format:'EAN13'},
];
export const allTools = [...qrTools,...barcodeTools];
export function toolBySlug(slug:string){return allTools.find(t=>t.slug===slug)}
export function sanitizeFilename(name:string){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'qrkit-code'}
export function checksum(digits:string){const nums=digits.split('').map(Number);let sum=0;nums.forEach((n,i)=>sum+=n*(i%2===0?1:3));return String((10-(sum%10))%10)}
export function normalizeRetail(value:string,type:'EAN13'|'UPC'|'ITF14'){const raw=value.replace(/\D/g,''); const lengths={EAN13:[12,13],UPC:[11,12],ITF14:[13,14]}[type]; if(!lengths.includes(raw.length)) return {value:raw,error:`Enter ${lengths[0]} or ${lengths[1]} digits.`}; const base=raw.slice(0,lengths[0]); const check=checksum(base); if(raw.length===lengths[1]&&raw.at(-1)!==check)return {value:raw,error:`Invalid ${type} checksum.`}; return {value:base+check,error:''}}
export function qrPayload(slug:string, value:string, extras:Record<string,string>={}){const v=value.trim(); if(slug==='wifi-qr-code') return `WIFI:T:${extras.security||'WPA'};S:${extras.ssid||v};P:${extras.password||''};H:${extras.hidden||'false'};;`; if(slug==='email-qr-code') return `mailto:${extras.email||v}?subject=${encodeURIComponent(extras.subject||'')}&body=${encodeURIComponent(extras.message||'')}`; if(slug==='phone-qr-code') return `tel:${v.replace(/[^+\d]/g,'')}`; if(slug==='sms-qr-code') return `SMSTO:${extras.phone||v}:${extras.message||''}`; if(slug==='vcard-qr-code') return `BEGIN:VCARD\nVERSION:3.0\nN:${extras.last||''};${extras.first||v}\nORG:${extras.org||''}\nTITLE:${extras.title||''}\nTEL:${extras.phone||''}\nEMAIL:${extras.email||''}\nURL:${extras.website||''}\nADR:${extras.address||''}\nEND:VCARD`; if(slug==='location-qr-code') return `geo:${extras.lat||v.split(',')[0]||'0'},${extras.lng||v.split(',')[1]||'0'}`; if(slug==='whatsapp-qr-code') return `https://wa.me/${(extras.phone||v).replace(/\D/g,'')}?text=${encodeURIComponent(extras.message||'')}`; if(slug==='event-qr-code') return `BEGIN:VEVENT\nSUMMARY:${extras.event||v}\nDTSTART:${extras.start||''}\nDTEND:${extras.end||''}\nLOCATION:${extras.location||''}\nDESCRIPTION:${extras.description||''}\nEND:VEVENT`; return v}
