/* QRKit Signal Paper: blog pages use an editorial reading column, clear article numbering, and one practical tool CTA. */
import RouteSeo from '../components/RouteSeo';
import { articles, articleBySlug } from '../lib/blog';
import { ArrowUpRight } from 'lucide-react';
import { Link } from 'wouter';

export function BlogIndex(){return <main className="container py-20"><RouteSeo title="QR Code & Barcode Guides | QRKit" description="Practical guides for QR codes, WiFi sharing, business cards, dynamic QR, Code 128, EAN-13, and UPC-A." path="/blog"/><div className="max-w-3xl"><p className="eyebrow">04 / Field notes</p><h1 className="mt-4 font-display text-5xl font-extrabold tracking-[-.06em] md:text-7xl">Guides for making codes work harder.</h1><p className="mt-6 text-lg leading-8 text-[#6f746d]">Short, practical notes on choosing a format, protecting the scan, and getting from a draft code to a dependable final file.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{articles.map((article,index)=><Link key={article.slug} href={`/blog/${article.slug}`} className="lift paper-panel scan-corners rounded-2xl border p-6"><div className="flex items-start justify-between"><span className="font-mono text-xs text-[#ff5b2e]">{String(index+1).padStart(2,'0')}</span><span className="font-mono text-[.65rem] uppercase tracking-wider text-[#6f746d]">{article.readTime}</span></div><h2 className="mt-12 font-display text-2xl font-bold tracking-[-.03em]">{article.title}</h2><p className="mt-3 text-sm leading-6 text-[#6f746d]">{article.excerpt}</p><span className="mt-7 inline-flex items-center gap-2 font-mono text-[.68rem] uppercase tracking-wider text-[#0e5b5d]">Read guide <ArrowUpRight size={14}/></span></Link>)}</div></main>}

export default function BlogArticle({slug}:{slug:string}){const article=articleBySlug(slug);if(!article)return <BlogIndex/>;return <main className="container py-20"><RouteSeo title={`${article.title} | QRKit`} description={article.excerpt} path={`/blog/${article.slug}`} type="article" breadcrumbs={[{name:'Home',path:'/'},{name:'Blog',path:'/blog'},{name:article.title,path:`/blog/${article.slug}`}]} /><div className="max-w-3xl"><Link href="/blog" className="font-mono text-xs uppercase tracking-wider text-[#0e5b5d]">← All field notes</Link><p className="eyebrow mt-10">Field note / {article.readTime}</p><h1 className="mt-4 font-display text-5xl font-extrabold leading-[.97] tracking-[-.07em] md:text-7xl">{article.title}</h1><p className="mt-7 text-xl leading-8 text-[#6f746d]">{article.excerpt}</p><div className="mt-14 space-y-12">{article.sections.map((section,index)=><section key={section.heading} className="border-t border-[#d7d0c4] pt-5"><p className="font-mono text-xs text-[#ff5b2e]">0{index+1}</p><h2 className="mt-5 font-display text-2xl font-bold">{section.heading}</h2><p className="mt-4 text-lg leading-8 text-[#5f655e]">{section.body}</p></section>)}</div><div className="mt-14 rounded-2xl bg-[#dce9e5] p-6"><p className="eyebrow">Make one now</p><p className="mt-3 font-display text-xl font-bold">Take the next step in the QRKit workbench.</p><Link href={article.toolPath} className="btn-secondary mt-5">Open related tool <ArrowUpRight size={15}/></Link></div></div></main>}
